export {
  LOCALE_CONDITIONAL_FEATURE_KEYS,
  RUNTIME_FEATURE_KEYS,
  anyEnabledFeatureIsLocaleConditional,
  isLocaleConditionalFeatureKey,
  isRuntimeFeatureKey,
  type RuntimeFeatureKey,
} from './feature-keys.ts';
export {
  getTrustedReviewerRuntimeConfig,
  getMultiPartyRuntimeConfig,
  getSafeAddressRuntimeConfig,
  getEmbedLimits,
  isCapabilityAvailability,
  isFormFeaturePolicyMode,
  isOrgFeaturePolicyMode,
  type CapabilityAvailability,
  type DisabledCause,
  type DisabledReason,
  type EmbedLimits,
  type FormFeaturePolicyMode,
  type FormRuntimePolicy,
  type InstanceCapabilities,
  type MultiPartyAssuranceFloor,
  type MultiPartyCardinality,
  type MultiPartyDeadlinePolicy,
  type MultiPartyExpirationAction,
  type MultiPartyInvitationChannel,
  type MultiPartyRoleClass,
  type MultiPartyRolePolicy,
  type MultiPartyRuntimeConfig,
  type MultiPartyTier,
  type MultiPartyVisibilityScope,
  type OrgFeaturePolicyMode,
  type OrgRuntimePolicy,
  type RecordLifecycleCorrectablePolicy,
  type RecordLifecycleDisputablePolicy,
  type RecordLifecyclePartyScope,
  type RecordLifecyclePolicy,
  type RecordLifecycleWindowPolicy,
  type RecordLifecycleWithdrawablePolicy,
  type ResolvedRecordLifecycleCorrectablePolicy,
  type ResolvedRecordLifecycleDisputablePolicy,
  type ResolvedRecordLifecyclePolicy,
  type ResolvedRecordLifecycleWindow,
  type ResolvedRecordLifecycleWithdrawablePolicy,
  type ResolvedRuntimeProfile,
  type ResolvedMultiPartyPolicy,
  type SafeAddressAccessClass,
  type SafeAddressFieldPolicy,
  type SafeAddressReceiptPostureTier,
  type SafeAddressRuntimeConfig,
  type TrustedReviewerRuntimeConfig,
} from './policy-shapes.ts';
export {
  EmbedOriginNotAllowedError,
  FeaturePolicyConflictError,
  InvalidRuntimePolicyError,
  OrgPolicyUnsatisfiedError,
  PaymentRequiresOnlineError,
  RuntimePolicyError,
  UnsupportedRequiredFeatureError,
  isRuntimePolicyError,
  type FeaturePolicyConflictKind,
  type RuntimePolicyDocumentKind,
  type RuntimePolicyErrorCode,
} from './errors.ts';
export {
  DEMO_STUB_ADAPTER,
  UNAVAILABLE_ADAPTER,
  isDemoStubAdapter,
  isUnavailableAdapter,
  markDemoStubAdapter,
  markUnavailableAdapter,
  type AdapterProvenanceMeta,
  type DemoStub,
  type DemoStubAdapterMeta,
  type Unavailable,
  type UnavailableAdapterMeta,
} from './sentinel.ts';
export {
  resolveRuntimeFeatures,
  type ResolveRuntimeFeaturesInput,
} from './resolver.ts';
export { FEATURE_PORT_MAP, type CompositionPortName } from './feature-port-map.ts';
export {
  CompositionIncoherenceError,
  assertCompositionCoherence,
  freezeComposition,
  type CompositionIncoherenceKind,
  type CompositionLike,
} from './composition-coherence.ts';
